name: CI-CD Pipeline (KIND)

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build & Push Docker Image
        run: |
          IMAGE=ghcr.io/jenishcloudengineer/myapp:latest
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Create KIND Cluster
        uses: helm/kind-action@v1.6.0

      - name: Deploy to KIND cluster
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      - name: Verify workloads
        run: |
          kubectl get pods -A
          kubectl get svc -A
